
theme: jekyll-theme-cayman
show_downloads: "true"
title: "Audio Pitch & Shift"
description: "Audio Pitch & Shift is a complete audio player intended to be useful for musicians who wants to slow down or change the pitch of the music."
author: "Starred MediaSoft"
plugins:
- jekyll-seo-tag
